spring.application.name=Backend

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=594233625626-1b20ndn5jccuekoklbmngj24mp172f4m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# application-dev.properties
spring.security.oauth2.client.registration.google.redirect-uri=https://localhost:8080/login/oauth2/code/google

# application-prod.properties
# spring.security.oauth2.client.registration.google.redirect-uri=https://decklybuy-backend.onrender.com/login/oauth2/code/google


# Ajustar al máximo de tamaño permitido
spring.servlet.multipart.max-file-size=40MB
spring.servlet.multipart.max-request-size=40MB

# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.agpwqpxapzienvfzjlpj
spring.datasource.password=PGZHVNTPAuCnOEh0

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de correo (JavaMailSender)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=decklybuy.app@gmail.com
spring.mail.password=ynqf ravc zpbl pwtm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Supabase Storage (Mapeado dinámico hacia archivo .env)
#supabase.url=${SUPABASE_URL}
#supabase.key=${SUPABASE_KEY}



# Cookie Sesión Persistente
server.servlet.session.cookie.secure=false

#HTTPS
server.port=8080
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=T0nyH4wk1999
server.ssl.key-store-type=PKCS12

server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.timeout=7d
