spring.application.name=Backend

spring.security.oauth2.client.registration.google.client-id=594233625626-1b20ndn5jccuekoklbmngj24mp172f4m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# ajustar al maximo de tamaño min.
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB